<?php
// File: public/debug_csrf.php

declare(strict_types=1);

require_once __DIR__ . '/../app/helpers/functions.php';

ensure_session();

header('Content-Type: text/plain');

echo "=== CSRF Debug ===\n\n";

// Token in session right now
echo "Session CSRF token: " . ($_SESSION['csrf_token'] ?? '[not set]') . "\n";

// Token being POSTed
echo "POST csrf_token: " . ($_POST['csrf_token'] ?? '[none in POST]') . "\n";

// Token being generated by helper
echo "Helper csrf_token(): " . csrf_token() . "\n";

// Method
echo "Request method: " . ($_SERVER['REQUEST_METHOD'] ?? 'unknown') . "\n";
