name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install FTP Deploy
        run: |
          sudo apt-get install -y lftp

      - name: Deploy to InfinityFree
        run: |
          lftp -e "
            set ftp:ssl-allow no;
            open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp://ftpupload.net;
            
            # ✅ Mirror the entire repo root into htdocs
            mirror -R ./ /htdocs \
              --ignore-time \
              --parallel=2 \
              --exclude .git/ \
              --exclude .github/ \
              --exclude README.md \
              --exclude LICENSE;

            bye
          "
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
